name = "my-anti-ob-bot"
main = "anti_ob_worker.js"
compatibility_date = "2025-08-20"

[triggers]
schedule = "0 */12 * * *"

[kv_namespaces]
  [kv_namespaces.CHAT_IDS]
  id = "YOUR_KV_NAMESPACE_ID"
